.

diff --git a/.github/workflows/test_dns.yml b/.github/workflows/test_dns.yml
--- a/.github/workflows/test_dns.yml
+++ b/.github/workflows/test_dns.yml
@@ -29,7 +29,7 @@ jobs:
         run: |
           echo -e "List the different names/addresses associsated with this host:\n\n"
           for opt in '-A' '-d' '-f'; do
-              echo "hostname $opt: $(hostname $opt 2>/dev/null || echo 'error')"
+              echo "hostname $opt: $(hostname $opt 2>/dev/null || echo '*error*')"
           done
 
       - name: nslookup
@@ -37,8 +37,9 @@ jobs:
         run: |
           echo -e "Expecting nslookup to return $(hostname -f)\n\n"
           for host in "$(hostname)" "$(hostname -f)"; do
-              echo "nslookup $host: $(nslookup "host" | sed -n "s/Name:\s*\(.*\)/\1/p")"
-              nslookup "host"
+              echo "nslookup $host: $(nslookup "$host" | sed -n "s/Name:\s*\(.*\)/\1/p")"
+                # echo "nslookup $host"
+              nslookup "$host"
           done
 
       - name: python.socket
